# Generated by Django 5.1.3 on 2024-12-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangamodel',
            name='image',
        ),
    ]
