# Generated by Django 5.1.3 on 2024-12-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_tags', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='BookReview',
        ),
    ]
