# Generated by Django 5.1.3 on 2024-12-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_tags', '0003_rename_review_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookReview', to='books_tags.book'),
        ),
    ]
