# Generated by Django 5.1.3 on 2024-12-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_tags', '0005_alter_bookreview_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookreview', to='books_tags.book'),
        ),
    ]
