# Generated by Django 5.1.3 on 2024-12-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_tags', '0006_alter_bookreview_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
