# Generated by Django 5.1.3 on 2024-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='library/', verbose_name='Загрузите фото фильма')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание')),
                ('price', models.FloatField(default=100, verbose_name='Укажите цену книги')),
                ('data', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Фэнтези', 'Фэнтези'), ('Романтика', 'Романтика'), ('Приключения', 'Приключения'), ('Комедия', 'Комедия'), ('Гарем', 'Гарем')], max_length=100)),
                ('time_watch', models.EmailField(blank=True, max_length=100, verbose_name='Укажите почту автора')),
                ('director', models.CharField(max_length=100, verbose_name='Укажите автора книги')),
            ],
        ),
    ]
