# Generated by Django 5.1.3 on 2024-12-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_model',
            name='advertising',
            field=models.URLField(null=True, verbose_name='Укажите ссылку на рекламу'),
        ),
    ]
