# Generated by Django 5.1.3 on 2024-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите ваше Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Укажите почту')),
                ('phone_number', models.FloatField(default='+996', verbose_name='Укажите номер телефона')),
                ('book', models.URLField(verbose_name='Укажите ссылку на книгу')),
            ],
        ),
    ]
