# Generated by Django 5.1.3 on 2024-12-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
        ('books_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='choice_check',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books_tags.book'),
        ),
    ]
